# encoding: utf-8

patch:
  "menu/page_size": 9
  schema_list:
    - schema: double_pinyin   # 自然码双拼
    - schema: emoji           # emoji 表情
  # switches:                   # 注意縮進
  #   - name: ascii_mode
  #     reset: 0                # reset 0 的作用是當從其他輸入方案切換到本方案時，
  #     states: [ 中文, 西文 ]  # 重設爲指定的狀態，而不保留在前一個方案中設定的狀態。
  #   - name: full_shape        # 選擇輸入方案後通常需要立即輸入中文，故重設 ascii_mode = 0；
  #     states: [ 半角, 全角 ]  # 而全／半角則可沿用之前方案中的用法。
  #   - name: simplification    # TODO: not work, add this line to double_pinyin.yaml will do
  #     reset: 1                # 增加這一行：默認啓用「繁→簡」轉換。
  #     states: [ 漢字, 汉字 ]
  # engine:
  #   filters:
  #     - simplifier  # 必要組件一
  #     - uniquifier  # 必要組件二
